### ISSUE TITLE
ProgressBar.println prints to stderr as default

### ISSUE THREAD

**Issue by silvioprog** [console-rs/indicatif#310] opened 2021-09-14 13:53 UTC
The smallest project to reproduce:

```rust
use indicatif::ProgressBar;

fn main() {
    let pb = ProgressBar::new_spinner();
    pb.println("Calculating...");
}
```

```bash
cargo build
./target/debug/app > msg.txt # Empty content 🙁
./target/debug/app 2> msg.txt # Filled content 🙂
```

Is this a bug or a behavior by design? (anyway, I solved in my project "temporary" using `ProgressDrawTarget::stdout()`)

cheers

**Comment by djc** [comment] 2021-09-15 07:04
Yes, I think this is by design. As I understand it, status information on the currently running command is usually printed to stderr, so that stdout can be used to print output data from the command (which can then conveniently be piped into a file).

**Comment by djc** [comment] 2022-02-22 10:21
Going to close this, feel free to reopen if you still think there is an issue.

**Closed by djc** 2022-02-22 10:21 UTC
