### ISSUE TITLE
0.17.0 release planning

### ISSUE THREAD

**Issue by jqnatividad** [console-rs/indicatif#318] opened 2021-10-26 15:16 UTC
There have been a lot of changes since 0.16.2 was released in May 2021.

https://github.com/mitsuhiko/indicatif/compare/0.16.2...main

Thanks for this awesome library!

**Comment by djc** [comment] 2021-12-15 09:13
Sorry this is taking so long. At this point I'm planning to put out an rc with a call for testing after #331 is merged.

**Comment by firasuke** [comment] 2022-01-02 18:15
I'm also waiting for a new release to use the new #301 feature.

**Comment by djc** [comment] 2022-01-02 21:35
I've published 0.17.0-rc.1, please test and 👍 this comment if it works for you!

**Comment by jqnatividad** [comment] 2022-01-31 04:41
Hi @djc,
I'm testing 0.17.0-rc.1 and I found per_secs is

**Comment by djc** [comment] 2022-02-01 09:52
Hey @jqnatividad, good question. Looks like I never even pushed the version bump to GitHub. Anyway, I've merged those changes into main now and pushed a tag. I also just published -rc.2 (and a tag for it).

**Comment by wbogocki** [comment] 2022-02-02 11:25
This is the output for 0.17.0-rc.2 for me, can make an issue if you'd like:

```
[#                   ] 0% 🥌 2421/525600 (216061.0691/s) ⏱ 00:00:00 (ETA 00:00:02) | Doing stuff...                                                                                                                                                                                                        [#                   ] 4% 🥌 19922/525600 (275073.6029/s) ⏱ 00:00:00 (ETA 00:00:01) | Doing stuff...                                                                                                                                                                                                       [##                  ] 7% 🥌 38170/525600 (274012.4835/s) ⏱ 00:00:00 (ETA 00:00:01) | Doing stuff...                                                                                                                                                                                                       [###                 ] 11% 🥌 56357/525600 (268608.7784/s) ⏱ 00:00:00 (ETA 00:00:01) | Doing stuff...                                                                                                                                                                                                      [###                 ] 14% 🥌 74228/525600 (265776.8413/s) ⏱ 00:00:00 (ETA 00:00:01) | Doing stuff...                                                                                                                                                                                                      [####                ] 17% 🥌 91943/525600 (264486.1798/s) ⏱ 00:00:00 (ETA 00:00:01) | Doing stuff...                                                                                                                                                                                                      [#####               ] 21% 🥌 109530/525600 (263163.4676/s) ⏱ 00:00:00 (ETA 00:00:01) | Doing stuff...                                                                                                                                                                                                     
[#####               ] 24% 🥌 127014/525600 (262198.9122/s) ⏱ 00:00:00 (ETA 00:00:01) | Doing stuff...                                                                                                                                                                                                     
[######              ] 27% 🥌 144495/525600 (262155.9439/s) ⏱ 00:00:00 (ETA 00:00:01) | Doing stuff...                                                                                                                                                                                                     
[#######             ] 31% 🥌 161966/525600 (262401.5976/s) ⏱ 00:00:00 (ETA 00:00:01) | Doing stuff...                                                                                                                                                                                                     
[#######             ] 34% 🥌 179478/525600 (263230.3474/s) ⏱ 00:00:00 (ETA 00:00:01) | Doing stuff...                                                                                                                                                                                                     
[########            ] 37% 🥌 197030/525600 (262241.7944/s) ⏱ 00:00:00 (ETA 00:00:01) | Doing stuff...                                                                                                                                                                                                     
[#########           ] 41% 🥌 214512/525600 (262512.2539/s) ⏱ 00:00:00 (ETA 00:00:01) | Doing stuff...                                                                                                                                                                                                     
[#########           ] 44% 🥌 232013/525600 (261348.6250/s) ⏱ 00:00:00 (ETA 00:00:01) | Doing stuff...                                                                                                                                                                                                     
[##########          ] 47% 🥌 249437/525600 (261426.8914/s) ⏱ 00:00:00 (ETA 00:00:01) | Doing stuff...                                                                                                                                                                                                     
[###########         ] 51% 🥌 266861/525600 (260778.5318/s) ⏱ 00:00:01 (ETA 00:00:00) | Doing stuff...                                                                                                                                                                                                     
[###########         ] 54% 🥌 284235/525600 (260765.6675/s) ⏱ 00:00:01 (ETA 00:00:00) | Doing stuff...                                                                                                                                                                                                     
[############        ] 57% 🥌 301616/525600 (260679.6394/s) ⏱ 00:00:01 (ETA 00:00:00) | Doing stuff...                                                                                                                                                                                                     
[#############       ] 61% 🥌 318988/525600 (260369.8677/s) ⏱ 00:00:01 (ETA 00:00:00) | Doing stuff...                                                                                                                                                                                                     
[#############       ] 64% 🥌 336349/525600 (260590.4877/s) ⏱ 00:00:01 (ETA 00:00:00) | Doing stuff...                                                                                                                                                                                                     
[##############      ] 67% 🥌 353723/525600 (260700.9683/s) ⏱ 00:00:01 (ETA 00:00:00) | Doing stuff...                                                                                                                                                                                                     
[###############     ] 71% 🥌 371106/525600 (260367.0554/s) ⏱ 00:00:01 (ETA 00:00:00) | Doing stuff...                                                                                                                                                                                                     
[###############     ] 74% 🥌 388465/525600 (260226.9450/s) ⏱ 00:00:01 (ETA 00:00:00) | Doing stuff...                                                                                                                                                                                                     
[################    ] 77% 🥌 405804/525600 (259551.2855/s) ⏱ 00:00:01 (ETA 00:00:00) | Doing stuff...                                                                                                                                                                                                     
[#################   ] 80% 🥌 423098/525600 (259005.1505/s) ⏱ 00:00:01 (ETA 00:00:00) | Doing stuff...                                                                                                                                                                                                     
[#################   ] 82% 🥌 431731/525600 (258381.1758/s) ⏱ 00:00:01 (ETA 00:00:00) | Doing stuff...                                                                                                                                                                                                     
[##################  ] 85% 🥌 448942/525600 (257905.5575/s) ⏱ 00:00:01 (ETA 00:00:00) | Doing stuff...                                                                                                                                                                                                     
[##################  ] 89% 🥌 466110/525600 (256801.1114/s) ⏱ 00:00:01 (ETA 00:00:00) | Doing stuff...                                                                                                                                                                                                     
[################### ] 92% 🥌 483227/525600 (256387.1104/s) ⏱ 00:00:01 (ETA 00:00:00) | Doing stuff...                                                                                                                                                                                                     
[####################] 95% 🥌 500304/525600 (256196.1187/s) ⏱ 00:00:01 (ETA 00:00:00) | Doing stuff...                                                                                                                                                                                                     
[####################] 97% 🥌 508843/525600 (254384.1073/s) ⏱ 00:00:02 (ETA 00:00:00) | Doing stuff...                                                                                                                                                                                                     
[####################] 100% 🥌 525600/525600 (254454.6886/s) ⏱ 00:00:02 (ETA 00:00:00) | Finished       
```

**Comment by sigmaSd** [comment] 2022-02-02 11:33
@wbogocki  it would be great if you make an issue with the code and terminal/os version

**Comment by wbogocki** [comment] 2022-02-02 11:47
Done :) Let me know if you need more info.

**Comment by djc** [comment] 2022-02-10 21:42
Published rc.4 to deal with a regression (#368) and squeezed in a further performance enhancement (see #363). Still inclined to release tomorrow barring any further regression reports.

**Comment by djc** [comment] 2022-02-22 10:35
Published rc.5. Really hoping to wrap this up soon.

**Comment by djc** [comment] 2022-07-26 21:25
@chris-laplante I'm inclined to push out the final release nowish. Any concerns? As far as I can tell the multi-line things (#443 and #447) won't affect the public API, and I think #447 is not a regression?

**Comment by chris-laplante** [comment] 2022-07-27 13:54
> @chris-laplante I'm inclined to push out the final release nowish. Any concerns? As far as I can tell the multi-line things (#443 and #447) won't affect the public API, and I think #447 is not a regression?

Yes I'd agree :). #447 is not a regression AFAICT.

**Comment by chris-laplante** [comment] 2022-07-28 16:38
> @chris-laplante I've written up release notes: https://github.com/console-rs/indicatif/releases/tag/0.17.0-rc.11. Would you be able to review them?

Nice writeup! Looks good to me :)

**Comment by djc** [comment] 2022-07-30 08:46
Released! Thanks everyone for their help!

**Closed by djc** 2022-07-30 08:46 UTC
