### ISSUE TITLE
Allow inc_length to reduce the length.

### ISSUE THREAD

**Issue by cassiersg** [console-rs/indicatif#237] opened 2021-02-08 10:27 UTC
I believe `ProgressBar::inc_length` should take a `i64` argument instead of `u64`. This would allow to shrink the progress bar length. (This is useful when the bar is initialized with an estimate of the number of items to process, and that estimate later diminishes.)

Maybe this should also be the case for `ProgressBar::inc`. I don't have a use case for that, but I guess it may happen.

**Comment by FibreFoX** [comment] 2021-02-13 14:39
Probably a duplicate of #236 ? So instead of incrementing with a negative number, maybe it should just have a way to re-set a new length.

**Comment by cassiersg** [comment] 2021-02-13 15:45
Not exactly a duplicate of #236, but related. See my proposal there.

**Comment by djc** [comment] 2022-02-22 09:49
d198f809c56868c8e998077eda3e3652e3a1c5fa adds a `ProgressBar::update()` method that allows the caller to mutate the `ProgressState` directly.

**Closed by djc** 2022-02-22 09:49 UTC
