### ISSUE TITLE
Broken template rendering with opt-level=z and lto=true

### ISSUE THREAD

**Issue by JMLX42** [console-rs/indicatif#88] opened 2019-02-16 22:20 UTC
Hello,

using `rustc` 1.32.0, ProgressBar rendering is broken when using `opt-level=z`.

I get the raw template (only `total_bytes` is actually templated):

```
{spinner:.green} [{elapsed_precise}] [{bar:30.cyan/blue}] {bytes}/207.49MB (4s)
```

instead of:

```
⠒ [00:00:01] [####>-------------------------] 27.67MB/207.49MB (6s)
```

Here is my code:

```
let pb = ProgressBar::new(size as u64);
            pb.set_style(ProgressStyle::default_bar()
                .template("{spinner:.green} [{elapsed_precise}] [{bar:40.cyan/blue}] {bytes}/{total_bytes} ({eta})")
                .progress_chars("#>-"));
            pb.enable_steady_tick(200);
            let mut progress = gpm::file::FileProgressWriter::new(
                file,
                size,
                |p : usize, _t : usize| {
                    pb.set_position(p as u64);
                }
            );

            lfs::resolve_lfs_link(
                remote.parse().unwrap(),
                Some(refspec.clone()),
                &package_path,
                &mut progress,
                key,
                passphrase,
            ).map_err(CommandError::IO)?;

            pb.finish();
```

It works as expected when setting `opt-level = "s"` or `lto = false`.

You can easily reproduce the issue by adding:

```toml
[profile.release]
opt-level = "z"
lto = true
```

to `Cargo.toml` and run `cargo run --release --example download`.

**Comment by djc** [comment] 2022-02-22 08:43
I cannot reproduce with your suggested reproduction scenario (and templating has been completely overhauled since this issue was created), so I'm going to close this for now. Feel free to reopen if you can still reproduce this!

**Closed by djc** 2022-02-22 08:43 UTC
