### ISSUE TITLE
Support for progress-bar terminal escape sequences

### ISSUE THREAD

**Issue by joshtriplett** [console-rs/indicatif#676] opened 2024-12-04 18:03 UTC
Multiple terminals, including recent Windows terminals and VTE/ptyxis support an OSC extension for reporting progress; the terminal can then indicate this progress in places like the tab title.

https://blogs.gnome.org/chergert/2024/12/03/ptyxis-progress-support/

https://github.com/microsoft/terminal/pull/8055

Please consider adding optional support for this OSC sequence in indicatif.

**Comment by chris-laplante** [comment] 2024-12-04 18:30
Duplicate of https://github.com/console-rs/indicatif/issues/596. Would definitely like to see this happen, although I won't personally have time to do it most likely :/.

Just thinking out loud - I also wonder how we should make it work when `MultiProgress` is in play and multiple progress bars are active...

**Closed by chris-laplante** 2024-12-04 18:30 UTC

**Comment by joshtriplett** [comment] 2024-12-04 19:57
Ah, sorry, I didn't see #596.

Regarding multi-progress: I think this is a reason to make it opt-in rather than automatic. People using multiple progress bars could choose which progress bar to opt in, or opt for some kind of summary or aggregation of the progress bars.

**Comment by chris-laplante** [comment] 2024-12-04 20:18
> Ah, sorry, I didn't see #596.
> 
> Regarding multi-progress: I think this is a reason to make it opt-in rather than automatic. People using multiple progress bars could choose which progress bar to opt in, or opt for some kind of summary or aggregation of the progress bars.

No worries! And yeah, that makes sense for multi progress - thanks for the ideas!
