### ISSUE TITLE
Bars are not properly cleared on refresh and leave ugly trail of lines for MultiProgressBar

### ISSUE THREAD

**Issue by Niedzwiedzw** [console-rs/indicatif#675] opened 2024-12-02 20:27 UTC
![image](https://github.com/user-attachments/assets/fcc407b1-1e9a-4f60-8d92-8641a88be800)

**Comment by chris-laplante** [comment] 2024-12-02 20:36
Can you share a link to the code? Or at least a snippet that reproduces the behavior?

**Comment by Niedzwiedzw** [comment] 2024-12-02 20:37
I'll do it later but I think it happens because new subbars are added dynamically

**Comment by Niedzwiedzw** [comment] 2024-12-02 20:42
I am monitoring a stream of tasks and once on task finishes another is immediately added, I think this causes a problem

**Comment by Niedzwiedzw** [comment] 2024-12-02 20:44
I'm also using         

pb.enable_steady_tick(std::time::Duration::from_millis(800));

not sure if this makes a difference


the config code is here:

https://github.com/Niedzwiedzw/hoolamike/blob/master/src/progress_bars.rs

**Comment by chris-laplante** [comment] 2024-12-02 20:54
> I'm also using
> 
> pb.enable_steady_tick(std::time::Duration::from_millis(800));
> 
> not sure if this makes a difference
> 
> the config code is here:
> 
> https://github.com/Niedzwiedzw/hoolamike/blob/master/src/progress_bars.rs

Ah, I see. The problem (which has been observed before, e.g. https://github.com/console-rs/indicatif/issues/502#issuecomment-1366016287) is that `MultiProgress` assumes that any `ProgressBar` you add to it hasn't been drawn yet. This is because `MultiProgress` is doing a ton of gymnastics to coordinate all the pbs under its purview, so when an independent pb draws to the screen, it messes everything up.

(@djc - I still don't know of a great way to fix the above or make it obvious in the API ☹️. `MultiProgress` is almost required to stand alone as a singleton or bad things happen)

You need to change your code so that any calls to `set_message` and `enable_steady_tick` are called on the pb after being added to `MultiProgress`, e.g.:

```rust
    let pb = PROGRESS_BAR.add(vertical_progress_bar(0, ProgressKind::Validate));
    pb.set_message("TOTAL");
    pb.enable_steady_tick(...)
```

**Comment by Niedzwiedzw** [comment] 2024-12-02 20:56
ah so .set_message is not lazy, ok

**Comment by chris-laplante** [comment] 2024-12-02 20:58
> ah so .set_message is not lazy, ok

To be honest I don't remember. `enable_steady_tick` is definitely not, and is more likely to be causing you issues here. But to be safe, avoid doing anything with the `ProgressBar` until it has been added to the `MultiProgress`.

**Comment by Niedzwiedzw** [comment] 2024-12-02 20:59
ok I'll just wrap it in a newtype with .attach() method xP

**Comment by Niedzwiedzw** [comment] 2024-12-02 21:11
```rust
type ProgressBarPostAttach = Arc<dyn Fn(&mut ProgressBar) + 'static>;

pub struct LazyProgressBar {
    bar: ProgressBar,
    post_attach: ProgressBarPostAttach,
}

impl LazyProgressBar {
    pub fn new(len: u64, post_attach: impl Fn(&mut ProgressBar) + 'static) -> Self {
        Self {
            bar: ProgressBar::new(len),
            post_attach: Arc::new(post_attach),
        }
    }

    pub fn attach_to(self, multi_progress: &MultiProgress) -> ProgressBar {
        let Self { bar, post_attach } = self;
        let mut bar = multi_progress.add(bar);
        post_attach(&mut bar);
        bar
    }
}

```


yes, now it works like a charm, thank you!

**Comment by Niedzwiedzw** [comment] 2024-12-02 21:28
one more question, I'm experimenting with 
`pb.with_finish(indicatif::ProgressFinish::AndLeave)`
but the screen is quickly filled up and no new bars appear, could they somehow go to the top of the screen in form of a log message to make space for new bars?

**Comment by chris-laplante** [comment] 2024-12-02 23:39
> one more question, I'm experimenting with `pb.with_finish(indicatif::ProgressFinish::AndLeave)` but the screen is quickly filled up and no new bars appear, could they somehow go to the top of the screen in form of a log message to make space for new bars?

Not sure about `with_finish`, but try playing with: https://docs.rs/indicatif/latest/indicatif/struct.MultiProgress.html#method.println

**Comment by chris-laplante** [comment] 2024-12-04 18:42
@Niedzwiedzw  is it OK if I close this then?

**Comment by Niedzwiedzw** [comment] 2024-12-04 18:44
yes yes, the issue is solved. great library!

**Comment by chris-laplante** [comment] 2024-12-04 18:45
> yes yes, the issue is solved. great library!

I can't take any credit for it, but glad to hear :).

**Closed** 2024-12-04 19:11 UTC
