### ISSUE TITLE
No way to disable that indicatif does not print to stdout/stderr if not running in a TTY

### ISSUE THREAD

**Issue by redzic** [console-rs/indicatif#335] opened 2021-12-16 16:45 UTC
In some scenarios, it is useful to still have indicatif print to stdout/stderr even if not running from a TTY, like when other applications are running your program from the shell and they want to parse your application's output (for example, ffmpeg or x264 print their progress when not running in a TTY, which makes it easy for other programs to parse their output).

It would be useful to have an option to change this behavior (and maybe some other feature like changing the template used and refresh rate of the progress bar when not running in a TTY). I could try implementing this if this feature would be valuable to have in indicatif.

**Comment by djc** [comment] 2021-12-16 17:39
I'm generally open to features like this as long as they reasonably fit with the design.

**Comment by djc** [comment] 2022-02-22 08:41
Duplicate of #87.

**Closed by djc** 2022-02-22 08:41 UTC
